For some reason this is causing issues for me in a simplified build environment.
error: expected primary-expression before ')' token
        263 |           __func__ FARM_MAYBE_VARGS(__VA_ARGS__)(__VA_ARGS__));